container.externalurl=https://localhost:7777
container.host=localhost
container.port=7777

container.security.credential.path=@credentialPath@
container.security.credential.password=@credentialPassword@
container.security.credential.format=@credentialFormat@
container.security.truststore.type=directory
container.security.truststore.directoryLocations.1=@truststorePath@

container.client.serverHostnameChecking=NONE

container.services.lifetime.default.JobManagement=2592000
container.services.lifetime.default.StorageManagement=2592000
container.services.lifetime.default=432000
container.services.registryEntryRefreshInterval=1800

persistence.directory=@data@
