<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    name="StorageFactory"
    targetNamespace="http://unigrids.org/2006/04/services/smf"
    xmlns:smf="http://unigrids.org/2006/04/services/smf"
    xmlns:wsrf-rp="http://docs.oasis-open.org/wsrf/rp-2"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  
  <wsdl:types>
    <xsd:schema xmlns:tsf="http://unigrids.org/2006/04/services/smf" 
    targetNamespace="http://unigrids.org/2006/04/services/smf">
	  <xsd:include schemaLocation="StorageFactory.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
  <!--  ========== Messages for CreateSMS  ============ --> 
  <wsdl:message name="CreateSMSRequest">
    <wsdl:part name="CreateSMSRequest"  element="smf:CreateSMS"/>
  </wsdl:message>
  <wsdl:message name="CreateSMSResponse">
    <wsdl:part name="CreateSMSResponse" element="smf:CreateSMSResponse"/>
  </wsdl:message>
  <wsdl:message name="SMSNotCreatedFault">
    <wsdl:part name="SMSNotCreatedFault" element="smf:TSRNotCreatedFault"/>
  </wsdl:message> 
  
  <!--  ========== Storage Factory Port Type  ============ --> 
  <wsdl:portType name="StorageFactory" wsrf-rp:ResourceProperties="smf:StorageFactoryProperties">
    <wsdl:operation name="CreateSMS">
      <wsdl:input  name="CreateSMSRequest" message="smf:CreateSMSRequest"/>
      <wsdl:output name="CreateSMSResponse" message="smf:CreateSMSResponse"/>
      <wsdl:fault  name="SMSNotCreatedFault" message="smf:SMSNotCreatedFault"/>
	</wsdl:operation>
  </wsdl:portType>
        
</wsdl:definitions>
