<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions 
    name="TargetSystemFactory"
    targetNamespace="http://unigrids.org/2006/04/services/tsf"
    xmlns:tsf="http://unigrids.org/2006/04/services/tsf"
    xmlns:wsrf-rp="http://docs.oasis-open.org/wsrf/rp-2"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  
  <wsdl:types>
    <xsd:schema xmlns:tsf="http://unigrids.org/2006/04/services/tsf" 
    targetNamespace="http://unigrids.org/2006/04/services/tsf">
	  <xsd:include schemaLocation="TargetSystemFactory.xsd"/>
    </xsd:schema>
  </wsdl:types>
  
  <!--  ========== Messages for CreateTSR  ============ --> 
  <wsdl:message name="CreateTSRRequest">
    <wsdl:part name="CreateTSRRequest"  element="tsf:CreateTSR"/>
  </wsdl:message>
  <wsdl:message name="CreateTSRResponse">
    <wsdl:part name="CreateTSRResponse" element="tsf:CreateTSRResponse"/>
  </wsdl:message>
  <wsdl:message name="TSRNotCreatedFault">
    <wsdl:part name="TSRNotCreatedFault" element="tsf:TSRNotCreatedFault"/>
  </wsdl:message> 
  
  <!--  ========== Target System Factory Port Type  ============ --> 
  <wsdl:portType name="TargetSystemFactory" wsrf-rp:ResourceProperties="tsf:TargetSystemFactoryProperties">
    <wsdl:operation name="CreateTSR">
      <wsdl:input  name="CreateTSRRequest" message="tsf:CreateTSRRequest"/>
      <wsdl:output name="CreateTSRResponse" message="tsf:CreateTSRResponse"/>
      <wsdl:fault  name="TSRNotCreatedFault" message="tsf:TSRNotCreatedFault"/>
	</wsdl:operation>
  </wsdl:portType>
        
</wsdl:definitions>
